// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/counter/data/counter.dart';
import 'features/note/data/note.dart';
import 'features/pattern/data/crochet_pattern.dart';
import 'features/project/data/crochet_project.dart';
import 'features/yarn/data/yarn.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5378978528683374602),
    name: 'Counter',
    lastPropertyId: const obx_int.IdUid(6, 589133721341823504),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3453328328882281627),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4123033809192450925),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4473443142890237668),
        name: 'value',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1939422218186573386),
        name: 'dateAdded',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2422153581660076194),
        name: 'counterTypeId',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 589133721341823504),
        name: 'linkedProjectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3283158433182953482),
        relationField: 'linkedProject',
        relationTarget: 'CrochetProject',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3941222417006982623),
    name: 'CrochetPattern',
    lastPropertyId: const obx_int.IdUid(7, 4245380848242571234),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5567719980043123409),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 243583493147183257),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 240580371403321315),
        name: 'dateAdded',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2534270522801004436),
        name: 'webLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8975451692242050310),
        name: 'ytLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 306671531749045047),
        name: 'pdfPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4245380848242571234),
        name: 'image',
        type: 23,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 8800463454997095893),
        name: 'linkedProjects',
        targetId: const obx_int.IdUid(3, 1356725143851871386),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 1356725143851871386),
    name: 'CrochetProject',
    lastPropertyId: const obx_int.IdUid(8, 364799222110378401),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 942330935117553610),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8896579687943549159),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8190834577946953482),
        name: 'dateAdded',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7075454764808975581),
        name: 'hooks',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7122146002206095942),
        name: 'linkedPatternId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 1732351365494030273),
        relationField: 'linkedPattern',
        relationTarget: 'CrochetPattern',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2476850564826503612),
        name: 'image',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8279358165492286538),
        name: 'icon',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 364799222110378401),
        name: 'progressId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 2779547033152406191),
        name: 'linkedYarn',
        targetId: const obx_int.IdUid(5, 17037979609883712),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'linkedCounters',
        srcEntity: 'Counter',
        srcField: 'linkedProject',
      ),
      obx_int.ModelBacklink(
        name: 'linkedNotes',
        srcEntity: 'Note',
        srcField: 'linkedProject',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 635915352324521449),
    name: 'Note',
    lastPropertyId: const obx_int.IdUid(4, 7541492491321514729),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3337164191063826787),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2407404769111278391),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4336527812821370760),
        name: 'dateAdded',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7541492491321514729),
        name: 'linkedProjectId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 6188727567967898901),
        relationField: 'linkedProject',
        relationTarget: 'CrochetProject',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 17037979609883712),
    name: 'Yarn',
    lastPropertyId: const obx_int.IdUid(11, 2780442833070518422),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5084958683484699349),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1556239057895256135),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2535830187243595895),
        name: 'dateAdded',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2886105853154992186),
        name: 'fiberContent',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9222646607757375775),
        name: 'fiberPercentage',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5866566580649484630),
        name: 'yarnWeight',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8521546584172229612),
        name: 'yarnLength',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5161338957117724266),
        name: 'recommendedHooks',
        type: 29,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4933237627975479966),
        name: 'yarnColors',
        type: 27,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 724713602538912453),
        name: 'image',
        type: 23,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2780442833070518422),
        name: 'weightCategoryId',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 1496050359394276461),
        name: 'linkedProjects',
        targetId: const obx_int.IdUid(3, 1356725143851871386),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 17037979609883712),
    lastIndexId: const obx_int.IdUid(3, 6188727567967898901),
    lastRelationId: const obx_int.IdUid(3, 1496050359394276461),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Counter: obx_int.EntityDefinition<Counter>(
      model: _entities[0],
      toOneRelations: (Counter object) => [object.linkedProject],
      toManyRelations: (Counter object) => {},
      getId: (Counter object) => object.id,
      setId: (Counter object, int id) {
        object.id = id;
      },
      objectToFB: (Counter object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.value);
        fbb.addInt64(3, object.dateAdded.millisecondsSinceEpoch);
        fbb.addInt64(4, object.counterTypeId);
        fbb.addInt64(5, object.linkedProject.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Counter()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..value = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..dateAdded = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          )
          ..counterTypeId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            12,
            0,
          );
        object.linkedProject.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        object.linkedProject.attach(store);
        return object;
      },
    ),
    CrochetPattern: obx_int.EntityDefinition<CrochetPattern>(
      model: _entities[1],
      toOneRelations: (CrochetPattern object) => [],
      toManyRelations: (CrochetPattern object) => {
        obx_int.RelInfo<CrochetPattern>.toMany(1, object.id):
            object.linkedProjects,
      },
      getId: (CrochetPattern object) => object.id,
      setId: (CrochetPattern object, int id) {
        object.id = id;
      },
      objectToFB: (CrochetPattern object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final webLinkOffset = object.webLink == null
            ? null
            : fbb.writeString(object.webLink!);
        final ytLinkOffset = object.ytLink == null
            ? null
            : fbb.writeString(object.ytLink!);
        final pdfPathOffset = object.pdfPath == null
            ? null
            : fbb.writeString(object.pdfPath!);
        final imageOffset = object.image == null
            ? null
            : fbb.writeListInt8(object.image!);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.dateAdded.millisecondsSinceEpoch);
        fbb.addOffset(3, webLinkOffset);
        fbb.addOffset(4, ytLinkOffset);
        fbb.addOffset(5, pdfPathOffset);
        fbb.addOffset(6, imageOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CrochetPattern()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..dateAdded = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..webLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..ytLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..pdfPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 14)
          ..image =
              const fb.Uint8ListReader(
                    lazy: false,
                  ).vTableGetNullable(buffer, rootOffset, 16)
                  as Uint8List?;
        obx_int.InternalToManyAccess.setRelInfo<CrochetPattern>(
          object.linkedProjects,
          store,
          obx_int.RelInfo<CrochetPattern>.toMany(1, object.id),
        );
        return object;
      },
    ),
    CrochetProject: obx_int.EntityDefinition<CrochetProject>(
      model: _entities[2],
      toOneRelations: (CrochetProject object) => [object.linkedPattern],
      toManyRelations: (CrochetProject object) => {
        obx_int.RelInfo<CrochetProject>.toMany(2, object.id): object.linkedYarn,
        obx_int.RelInfo<Counter>.toOneBacklink(
          6,
          object.id,
          (Counter srcObject) => srcObject.linkedProject,
        ): object.linkedCounters,
        obx_int.RelInfo<Note>.toOneBacklink(
          4,
          object.id,
          (Note srcObject) => srcObject.linkedProject,
        ): object.linkedNotes,
      },
      getId: (CrochetProject object) => object.id,
      setId: (CrochetProject object, int id) {
        object.id = id;
      },
      objectToFB: (CrochetProject object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final hooksOffset = object.hooks == null
            ? null
            : fbb.writeListFloat64(object.hooks!);
        final imageOffset = object.image == null
            ? null
            : fbb.writeListInt8(object.image!);
        final iconOffset = fbb.writeString(object.icon);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.dateAdded.millisecondsSinceEpoch);
        fbb.addOffset(3, hooksOffset);
        fbb.addInt64(4, object.linkedPattern.targetId);
        fbb.addOffset(5, imageOffset);
        fbb.addOffset(6, iconOffset);
        fbb.addInt64(7, object.progressId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CrochetProject()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..dateAdded = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..hooks = const fb.ListReader<double>(
            fb.Float64Reader(),
            lazy: false,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..image =
              const fb.Uint8ListReader(
                    lazy: false,
                  ).vTableGetNullable(buffer, rootOffset, 14)
                  as Uint8List?
          ..icon = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..progressId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          );
        object.linkedPattern.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.linkedPattern.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<CrochetProject>(
          object.linkedYarn,
          store,
          obx_int.RelInfo<CrochetProject>.toMany(2, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<CrochetProject>(
          object.linkedCounters,
          store,
          obx_int.RelInfo<Counter>.toOneBacklink(
            6,
            object.id,
            (Counter srcObject) => srcObject.linkedProject,
          ),
        );
        obx_int.InternalToManyAccess.setRelInfo<CrochetProject>(
          object.linkedNotes,
          store,
          obx_int.RelInfo<Note>.toOneBacklink(
            4,
            object.id,
            (Note srcObject) => srcObject.linkedProject,
          ),
        );
        return object;
      },
    ),
    Note: obx_int.EntityDefinition<Note>(
      model: _entities[3],
      toOneRelations: (Note object) => [object.linkedProject],
      toManyRelations: (Note object) => {},
      getId: (Note object) => object.id,
      setId: (Note object, int id) {
        object.id = id;
      },
      objectToFB: (Note object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addInt64(2, object.dateAdded.millisecondsSinceEpoch);
        fbb.addInt64(3, object.linkedProject.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Note()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..content = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..dateAdded = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          );
        object.linkedProject.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        object.linkedProject.attach(store);
        return object;
      },
    ),
    Yarn: obx_int.EntityDefinition<Yarn>(
      model: _entities[4],
      toOneRelations: (Yarn object) => [],
      toManyRelations: (Yarn object) => {
        obx_int.RelInfo<Yarn>.toMany(3, object.id): object.linkedProjects,
      },
      getId: (Yarn object) => object.id,
      setId: (Yarn object, int id) {
        object.id = id;
      },
      objectToFB: (Yarn object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final fiberContentOffset = object.fiberContent == null
            ? null
            : fbb.writeList(
                object.fiberContent!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        final fiberPercentageOffset = object.fiberPercentage == null
            ? null
            : fbb.writeListInt64(object.fiberPercentage!);
        final recommendedHooksOffset = object.recommendedHooks == null
            ? null
            : fbb.writeListFloat64(object.recommendedHooks!);
        final yarnColorsOffset = fbb.writeListInt64(object.yarnColors);
        final imageOffset = object.image == null
            ? null
            : fbb.writeListInt8(object.image!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.dateAdded.millisecondsSinceEpoch);
        fbb.addOffset(3, fiberContentOffset);
        fbb.addOffset(4, fiberPercentageOffset);
        fbb.addFloat64(5, object.yarnWeight);
        fbb.addInt64(6, object.yarnLength);
        fbb.addOffset(7, recommendedHooksOffset);
        fbb.addOffset(8, yarnColorsOffset);
        fbb.addOffset(9, imageOffset);
        fbb.addInt64(10, object.weightCategoryId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = Yarn()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..dateAdded = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
          )
          ..fiberContent = const fb.ListReader<String>(
            fb.StringReader(asciiOptimization: true),
            lazy: false,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..fiberPercentage = const fb.ListReader<int>(
            fb.Int64Reader(),
            lazy: false,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..yarnWeight = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            14,
          )
          ..yarnLength = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            16,
          )
          ..recommendedHooks = const fb.ListReader<double>(
            fb.Float64Reader(),
            lazy: false,
          ).vTableGetNullable(buffer, rootOffset, 18)
          ..yarnColors = const fb.ListReader<int>(
            fb.Int64Reader(),
            lazy: false,
          ).vTableGet(buffer, rootOffset, 20, [])
          ..image =
              const fb.Uint8ListReader(
                    lazy: false,
                  ).vTableGetNullable(buffer, rootOffset, 22)
                  as Uint8List?
          ..weightCategoryId = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            24,
            0,
          );
        obx_int.InternalToManyAccess.setRelInfo<Yarn>(
          object.linkedProjects,
          store,
          obx_int.RelInfo<Yarn>.toMany(3, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Counter] entity fields to define ObjectBox queries.
class Counter_ {
  /// See [Counter.id].
  static final id = obx.QueryIntegerProperty<Counter>(
    _entities[0].properties[0],
  );

  /// See [Counter.name].
  static final name = obx.QueryStringProperty<Counter>(
    _entities[0].properties[1],
  );

  /// See [Counter.value].
  static final value = obx.QueryIntegerProperty<Counter>(
    _entities[0].properties[2],
  );

  /// See [Counter.dateAdded].
  static final dateAdded = obx.QueryDateProperty<Counter>(
    _entities[0].properties[3],
  );

  /// See [Counter.counterTypeId].
  static final counterTypeId = obx.QueryIntegerProperty<Counter>(
    _entities[0].properties[4],
  );

  /// See [Counter.linkedProject].
  static final linkedProject = obx.QueryRelationToOne<Counter, CrochetProject>(
    _entities[0].properties[5],
  );
}

/// [CrochetPattern] entity fields to define ObjectBox queries.
class CrochetPattern_ {
  /// See [CrochetPattern.id].
  static final id = obx.QueryIntegerProperty<CrochetPattern>(
    _entities[1].properties[0],
  );

  /// See [CrochetPattern.name].
  static final name = obx.QueryStringProperty<CrochetPattern>(
    _entities[1].properties[1],
  );

  /// See [CrochetPattern.dateAdded].
  static final dateAdded = obx.QueryDateProperty<CrochetPattern>(
    _entities[1].properties[2],
  );

  /// See [CrochetPattern.webLink].
  static final webLink = obx.QueryStringProperty<CrochetPattern>(
    _entities[1].properties[3],
  );

  /// See [CrochetPattern.ytLink].
  static final ytLink = obx.QueryStringProperty<CrochetPattern>(
    _entities[1].properties[4],
  );

  /// See [CrochetPattern.pdfPath].
  static final pdfPath = obx.QueryStringProperty<CrochetPattern>(
    _entities[1].properties[5],
  );

  /// See [CrochetPattern.image].
  static final image = obx.QueryByteVectorProperty<CrochetPattern>(
    _entities[1].properties[6],
  );

  /// see [CrochetPattern.linkedProjects]
  static final linkedProjects =
      obx.QueryRelationToMany<CrochetPattern, CrochetProject>(
        _entities[1].relations[0],
      );
}

/// [CrochetProject] entity fields to define ObjectBox queries.
class CrochetProject_ {
  /// See [CrochetProject.id].
  static final id = obx.QueryIntegerProperty<CrochetProject>(
    _entities[2].properties[0],
  );

  /// See [CrochetProject.name].
  static final name = obx.QueryStringProperty<CrochetProject>(
    _entities[2].properties[1],
  );

  /// See [CrochetProject.dateAdded].
  static final dateAdded = obx.QueryDateProperty<CrochetProject>(
    _entities[2].properties[2],
  );

  /// See [CrochetProject.hooks].
  static final hooks = obx.QueryDoubleVectorProperty<CrochetProject>(
    _entities[2].properties[3],
  );

  /// See [CrochetProject.linkedPattern].
  static final linkedPattern =
      obx.QueryRelationToOne<CrochetProject, CrochetPattern>(
        _entities[2].properties[4],
      );

  /// See [CrochetProject.image].
  static final image = obx.QueryByteVectorProperty<CrochetProject>(
    _entities[2].properties[5],
  );

  /// See [CrochetProject.icon].
  static final icon = obx.QueryStringProperty<CrochetProject>(
    _entities[2].properties[6],
  );

  /// See [CrochetProject.progressId].
  static final progressId = obx.QueryIntegerProperty<CrochetProject>(
    _entities[2].properties[7],
  );

  /// see [CrochetProject.linkedYarn]
  static final linkedYarn = obx.QueryRelationToMany<CrochetProject, Yarn>(
    _entities[2].relations[0],
  );

  /// see [CrochetProject.linkedCounters]
  static final linkedCounters =
      obx.QueryBacklinkToMany<Counter, CrochetProject>(Counter_.linkedProject);

  /// see [CrochetProject.linkedNotes]
  static final linkedNotes = obx.QueryBacklinkToMany<Note, CrochetProject>(
    Note_.linkedProject,
  );
}

/// [Note] entity fields to define ObjectBox queries.
class Note_ {
  /// See [Note.id].
  static final id = obx.QueryIntegerProperty<Note>(_entities[3].properties[0]);

  /// See [Note.content].
  static final content = obx.QueryStringProperty<Note>(
    _entities[3].properties[1],
  );

  /// See [Note.dateAdded].
  static final dateAdded = obx.QueryDateProperty<Note>(
    _entities[3].properties[2],
  );

  /// See [Note.linkedProject].
  static final linkedProject = obx.QueryRelationToOne<Note, CrochetProject>(
    _entities[3].properties[3],
  );
}

/// [Yarn] entity fields to define ObjectBox queries.
class Yarn_ {
  /// See [Yarn.id].
  static final id = obx.QueryIntegerProperty<Yarn>(_entities[4].properties[0]);

  /// See [Yarn.name].
  static final name = obx.QueryStringProperty<Yarn>(_entities[4].properties[1]);

  /// See [Yarn.dateAdded].
  static final dateAdded = obx.QueryDateProperty<Yarn>(
    _entities[4].properties[2],
  );

  /// See [Yarn.fiberContent].
  static final fiberContent = obx.QueryStringVectorProperty<Yarn>(
    _entities[4].properties[3],
  );

  /// See [Yarn.fiberPercentage].
  static final fiberPercentage = obx.QueryIntegerVectorProperty<Yarn>(
    _entities[4].properties[4],
  );

  /// See [Yarn.yarnWeight].
  static final yarnWeight = obx.QueryDoubleProperty<Yarn>(
    _entities[4].properties[5],
  );

  /// See [Yarn.yarnLength].
  static final yarnLength = obx.QueryIntegerProperty<Yarn>(
    _entities[4].properties[6],
  );

  /// See [Yarn.recommendedHooks].
  static final recommendedHooks = obx.QueryDoubleVectorProperty<Yarn>(
    _entities[4].properties[7],
  );

  /// See [Yarn.yarnColors].
  static final yarnColors = obx.QueryIntegerVectorProperty<Yarn>(
    _entities[4].properties[8],
  );

  /// See [Yarn.image].
  static final image = obx.QueryByteVectorProperty<Yarn>(
    _entities[4].properties[9],
  );

  /// See [Yarn.weightCategoryId].
  static final weightCategoryId = obx.QueryIntegerProperty<Yarn>(
    _entities[4].properties[10],
  );

  /// see [Yarn.linkedProjects]
  static final linkedProjects = obx.QueryRelationToMany<Yarn, CrochetProject>(
    _entities[4].relations[0],
  );
}
